ProductCatalog/Models/ErrorViewModel.cs
namespace ProductCatalog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductCatalog/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProductCatalog.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Не указан Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ProductCatalog/Models/PageDeleteRequestModel.cs
namespace ProductCatalog.Models
{
    public class PageDeleteRequestModel
    {
        public int PageId { get; set; }
    }
}

ProductCatalog/Models/ProductPageModel.cs
namespace ProductCatalog.Models
{
    public class ProductPageModel
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Product { get; set; }
        public string ProductGroup { get; set; }
        public string Ecom { get; set; }
        public string ContentType { get; set; }
    }
}

ProductCatalog/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Dal.Repository;
using ProductCatalog.Domain.Entity;
using ProductCatalog.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;

namespace ProductCatalog.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserRepository _repository;
        public AccountController(UserRepository repository)
        {
            _repository = repository;
        }
        [Route("/login")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [Route("/login")]
        // POST: AccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IResult> Login(LoginModel login)
        {
            if (ModelState.IsValid)
            {
                User? user = _repository.GetUser(login);
                if (user != null)
                {
                    var claims = new List<Claim> { new Claim(ClaimTypes.Name, login.Email) };
                    ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity));

                    return Results.Redirect("/");
                    
                }
            }
            return Results.Unauthorized();
        }

        [Route("/logout")]
        [HttpGet]
        public async Task<IResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Results.Redirect("/login");
        }

    }
}

ProductCatalog/Controllers/CategoryDetailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Dal.Repository;
using ProductCatalog.Domain.Entity;
using ProductCatalog.Models;

namespace ProductCatalog.Controllers
{
    [Authorize]
    public class CategoryDetailController : Controller
    {
        private readonly ProductPageRepository _repository;

        public CategoryDetailController(ProductPageRepository repository)
        {
            _repository = repository;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(ProductCategory category)
        {
            _repository.CreateProductCategory(category);
            try
            {
                return Redirect(Request?.Headers["Referer"]);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGroup(ProductGroup group)
        {
            _repository.CreateProductGroup(group);
            try
            {
                return Redirect(Request?.Headers["Referer"]);
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryDetail/Details/5
        public ActionResult Details(int id)
        {
            ProductCategory? category = _repository
                .GetCategoryById(id);
            return View(category);
        }

        // POST: CategoryDetail/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductPage collection)
        {
            _repository.CreateProductPage(collection);
            try
            {
                return Redirect(Request?.Headers["Referer"]);
            }
            catch
            {
                return View();
            }
        }

        // POST: CategoryDetail/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProductPage(ProductPage page)
        {
            _repository.EditProductPage(page);
            
            try
            {

                return Redirect(Request?.Headers["Referer"]);
            }
            catch
            {
                return View();
            }
        }

        // POST: CategoryDetail/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PageDeleteRequestModel deleteRequest)
        {
            var item = _repository.GetPageById(deleteRequest.PageId);

            if (item == null)
            {
                return Redirect(Request?.Headers["Referer"]);
            }
            _repository.DeletePage(item);
            return Redirect(Request?.Headers["Referer"]);


        }
    }
}

ProductCatalog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Dal.Repository;
using ProductCatalog.Models;
using System.Diagnostics;

namespace ProductCatalog.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ProductPageRepository _repository;

        public HomeController(ILogger<HomeController> logger,
            ProductPageRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            var category = _repository
               .GetAllCategory();
            return View(category);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductCatalog/Views/CategoryDetail/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ProductCatalog/Views/CategoryDetail/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ProductCatalog/Views/Home/Index.cshtml
@using ProductCatalog.Domain.Entity;
@using ProductCatalog.Models;
@model IList<ProductCategory>;
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center" style="margin-bottom:20px;">
    <h1 class="display-4">Product Catalog Pages</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a
@*         asp-controller="CategoryController"
       asp-action="Create" *@
       type="button"
       class="btn btn-primary"
       data-bs-toggle="modal"
       /data-bs-target="#createCategoryModal"
       style="margin-bottom:20px;">
        Add New Product
    </a>
</div>


<div class="row">
    @foreach (var item in Model)
    {
    <div class="col-sm-4" style="margin-bottom:20px;">
        <div class="mp-card card text-center">
            <div class="card-body">
                <h5 class="card-title">@item.Product</h5>
                <p class="card-text">Раздел содержит страницы продукта @item.Product.</p>
                <a 
                    href="CategoryDetail/Details/@item.Id" 
                    class="btn btn-primary"
                >
                    Detail
                </a>
            </div>
        </div>
    </div>
    }
</div>


<!-- Create Category Modal -->
<div class="modal fade" id="createCategoryModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create new product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="CategoryDetail"
                      asp-action="CreateCategory"
                      method="post">
                    <div class="input-group input-group-sm mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-sm" style="width:120px;"><b>Product: </b></span>
                        <input type="text"
                               class="form-control"
                               name="Product"
                        />
                    </div>
                    <div class="mb-3 form-check">
                        <input required type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Create ?</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

ProductCatalog/Views/Shared/_Layout.cshtml
@using ProductCatalog.Domain.Entity;

@{

}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductCatalog</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductCatalog.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductCatalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a 
                                class="nav-link text-dark" 
                                href="/login"
                            >
                                LogIn
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="/logout">
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>